apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTERAPICLUSTER 
    machine.openshift.io/cluster-api-machine-role: master 
    machine.openshift.io/cluster-api-machine-type: master 
  name: CLUSTERAPIMS
  namespace: MSNS
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTERAPICLUSTER 
      machine.openshift.io/cluster-api-machineset: CLUSTERAPIMS
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTERAPICLUSTER
        machine.openshift.io/cluster-api-machine-role: master 
        machine.openshift.io/cluster-api-machine-type: master
        machine.openshift.io/cluster-api-machineset: CLUSTERAPIMS
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/master: "" 
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: CSNM
            namespace: CSNS
          image:
            offer: "OFFER"
            publisher: "IMP"
            resourceID: ""
            sku: "VMSKU"
            version: "VMVER"
          internalLoadBalancer: "ILP"
          kind: AzureMachineProviderSpec
          location: VMREGION
          managedIdentity: "MI"
          metadata:
            creationTimestamp: null
          networkResourceGroup: "NETRG"
          osDisk:
            diskSizeGB: DISKSIZE
            managedDisk:
              storageAccountType: SAT
            osType: Linux
          publicIP: PIP
          publicLoadBalancer: "PL"
          resourceGroup: NODERG 
          subnet: MASTERSUBNET   
          userDataSecret:
            name: MUDSN 
          vmSize: VMSIZE
          vnet: MASTERVNET 
          zone: "VMZONE" 
